### ISSUE TITLE
XyzTransition doesn't inherit or apply attributes

### ISSUE THREAD

**Issue by Sananes** [ingram-projects/animxyz#23]
Hey buddy,

Sorry to be a pain again. One thing I've noticed. I'm trying to come up with a component that includes both `XyzTransition` and `XyzTransitionGroup`. The problem is, the `XyzTransition` doesn't apply the v-observe-visibility directive argument. But for `XyzTransitionGroup` it seems to work just fine. 

If I wrap this entire component in a div and add the directive there, it works. Only issue is I now will always have an extra div placed in there, which is not ideal.

Would love to know your thoughts?

 I've set the component up like this:

`components/Animation.vue`
```
<template>
  <component
    v-bind:is="group ? 'XyzTransitionGroup' : 'XyzTransition'"
    v-bind="this.$attrs"
    v-bind:on="this.$listeners"
    v-observe-visibility="{ callback: visiblityChanged, ...options }"
  >
    <slot v-if="isVisible" />
  </component>
</template>

<script>
export default {
  name: 'Animation',
  props: {
    // Options for vue observer
    options: {
      type: Object,
      default: () => {},
      required: false,
    },
    // Wether its a group transition
    group: {
      type: Boolean,
      required: false,
    },
  },
  data() {
    return {
      isVisible: false,
    }
  },
  methods: {
    visiblityChanged(isVisible, event) {
      this.isVisible = isVisible
    },
  },
}
</script>
```

Again, thanks for all your help!

**Comment by Sananes** [comment]
After some digging I tried to look into the work and found that `XyzTransition.js` in the library has a very strict attribute here around line `26`:
[https://github.com/ingram-projects/animxyz/blob/master/packages/vue/src/components/XyzTransition.js](url)

Adding this helped me:

```
		context.children.forEach((child) => {
			child.data = mergeData(
				{
					attrs: {
						xyz: data.attrs.xyz,
						
						// Added this here
                                                ...content.data.attrs
					},
					directives: data.directives,
					staticStyle: data.staticStyle,
					style: data.style,
				},
				child.data
			)
		})
```

**Comment by milesingrams** [comment]
Hi Sananes!
I will also look into this. In the current prerelease version I am trying a new dataMerge tool that may solve the current issue https://github.com/alexsasharegan/vue-functional-data-merge.
If the new data merge doesn't work I will try to do something similar to what you are suggesting but I have to make sure it only passes attributes that are not relevant to the transition component. AKA that it ignores `appear`, `duration`, `mode`, etc.
Since these are parsed into `context.props` I think it should be fine, but just want to double check.

**Comment by Sananes** [comment]
Makes total sense my man! Sounds good to me, either way I have a workaround for now. But love the direction your heading at!

**Comment by milesingrams** [comment]
This should be resolved in the latest release v0.2.0! Let me know if it works for you and thanks for helping us improve :)

**Comment by Sananes** [comment]
You’re awesome @milesingrams! Thanks a bunch and happy new year to you!

**Comment by Sananes** [comment]
@milesingrams Hey my good buddy! Unfortunately I didn't actually get a chance to test this the other day. But unfortunately, it's still not inheriting values. Here's an example of what I have going:

```
  <XyzTransition
    v-bind="this.$attrs"
    v-bind:on="this.$listeners"
    v-observe-visibility="{ callback: visiblityChanged, ...options }"
  >
    <slot v-if="isVisible" />
  </XyzTransition>
```

The slot itself isn't inheriting the attributes. This works perfectly fine for XyzTransitionGroup though?

**Comment by milesingrams** [comment]
Hi Sasanes. I believe this is more an issue of how v-observe-visibility works with v-if. Basically v-observe-visibility watches an existing DOM element to see if it comes into the viewport.

With XyzTransitionGroup (And Vue's native TransitionGroup), there is always a wrapper element which can be observed whether or not the child elements exist.

However with XyzTransition (And Vue's native Transition) it is a higher-order-component meaning it only renders it's children and does not have a wrapping element. When v-if is false on the child of XyzTransition, the component renders 0 DOM elements and therefore does not have any elements to attach the observe-visibility handler to.

The only way to get this to work with XyzTransition would be to wrap the transition in a div with the observer on it. I have implemented this in a codesandbox to show how it might work. If you scroll up and down you will see the elements appear.

https://codesandbox.io/s/animxyz-observe-visibility-test-71tu9?file=/src/components/Animation.vue

**Comment by milesingrams** [comment]
The codepen solution is quite buggy though. I think the only way to properly implement this would be a v-visible directive which would toggle between 'visibility: visible' and 'visibility: hidden' instead of v-if or v-show. This is easy using a custom directive but it still doesn't trigger the transitions since 'v-show' and 'v-if' are special directives and trigger transitions at a core level. Hopefully I can find a way.

I'm trying to find a solution to this too so I can natively add v-observe-visibility properties. But so far it's proven difficult.

https://github.com/vuejs/vue/issues/5425

I'll keep trying and keep you updated. Also please let me know if you find a way!
